// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpohujzgfnjodabemizx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwb2h1anpnZm5qb2RhYmVtaXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTk5NjEsImV4cCI6MjA1NzU5NTk2MX0.3ePVNrwcmex1ekfz5jjdl46kBn3Detb2T8MIOqoTLkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);